### PR TITLE
Adding text-decoration-line property and Bold/Italic font simulation

### PR DESCRIPTION
**Pull request by tnas**
The text-decoration-line property was added to CssConstants. Consequently, the FontStyleApplierUtil  and DefaultCssResolver were changed in order to process this new property.  I used the TestDecorationTest to test my modifications. All 8 test cases have been run without failure.

### CODE REVIEW

**Comment by tnas** [comment]
Hi,
I've fixed the problem with bold/italic font simulation. However, I cannot move the simulation logic to the FontProvider level since this class is part of the layout package of IText (I didn't fork the IText project). So, I made the implementation in the ConverterProperties anyway.

**Comment by avlemos** [comment]
Hi @tnas,

We are currently analysing this PR. We should have news for you shortly.

Thank you,
André

**Comment by LodrKumquat** [comment]
Hi @tnas,

Since our current develop has moved forward, meaning there are conflicts now with this PR, and to make it more convenient to verify the solution you've introduced in the PR, I would like to kindly ask you to rebase your changes on the top of our current develop. Please make sure to rebase and not merge them in order to make history visualize the newly implemented features only. Merge-commits aren't favored for they entangle the history making it less transparent, therefore no merge-commits should be present in a pull-request, including merging itext's changes into your previous changes. Also the rebased commits including your feautures implementations need to be squashed: meaning, reorganized in such a way so that there are two separate commits: one including full solution for text-decoration-line and its tests and the other one including bold/italic simulation and its tests, since they are two separate features. Please make sure that both of the commits introduce comprehensive solution for the corresponding issues.

Thank you,
Valera

**Comment by BlackEgoist** [comment]
Hi Thiago!
Thanks for you contribution. I would like to provide you with more info about the recent changes concerning your PR.

Regarding text-decoration-line properties, it was recently implemented by our team, however, we took a slightly different approach and implemented partial support for text-decoration-color and text-decoration-style as well.

As for the bold/italic simulation, we will not implement it for now, as the feature should be implemented on another code level. We expect to see it in FontProvider and related classes. One of the key reasons for this is that it's highly undesired to use simulation if the real italic/bold fonts are available. In the future we might add this functionality properly. There are a few workarounds: specify exact font explicitly through alias in font-provider, make sure shipped fonts are allowed to be used in the default font-provider (we have some bold/italic fonts shipped together with pdfHTML), add custom font to font-provider, apply bold/italic simulation to layout elements after HtmlConverter#convertToElements call or using custom CssApplier for the HTML elements.

The pull request will be closed soon. Your contribution suggestions are always welcome.

**Pull request closed without merging**
